# Website Header, Description, Footer year, and text. 
# Update these fields to reflect your new intro.

heading: "Antony Willbert's Digital Garden"  # Updated heading for your website
content: "Exploring Health, Mental Wellness, Relationships, and Wealth"  # Updated description based on your focus areas

copyright:  
  year: © 2024
  msg: Contents under CC-BY-NC 

# URL and Base URL Settings
url: "https://antonywillbert.github.io" # Keep this as is (if you're using this domain)

baseurl: ""  # No changes needed here if your site isn't in a subfolder.

# Preferences for the site.
preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true
  homepage: 
    enabled: true ## Ensures you have a homepage. Customize _includes/Homepage.html to reflect your intro text

# Set title and content for private & broken link tooltip
privatelinks:
  title: Private or Broken Links
  msg: The page you're looking for is either not available or private!

# Build settings
theme: null  # Keep as is

plugins:
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy
    
## Enable Collections
collections:
    notes:
      output: true
      permalink: /note/:title

# Markdown and Sass settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  
sass:
  style: compressed

# Excluded directories
exclude:
  - _notes/000 Inbox
  - _notes/200 Private
  - _notes/300 Templates
